//! MCP server exposing the rfc-index library as tools over stdio.
//!
//! Build with: `cargo build --bin rfc-mcp`
//! Register with Claude Code (or Claude Desktop / Cursor / etc.) by pointing
//! the MCP client at the resulting binary; it uses stdio transport.

use std::sync::{Arc, Mutex};

use rfc_index::{FacetKind, RfcIndex, RfcQuery, SeriesKind};
use rmcp::{
    ErrorData as McpError, ServerHandler, ServiceExt,
    handler::server::{router::tool::ToolRouter, wrapper::Parameters},
    model::*,
    schemars, tool, tool_handler, tool_router,
    transport::stdio,
};
use serde::Deserialize;
use serde_json::{Value, json};

#[derive(Clone)]
struct Server {
    idx: Arc<Mutex<RfcIndex>>,
    // Read by the `#[tool_handler]` macro via a method generated by `#[tool_router]`.
    #[allow(dead_code)]
    tool_router: ToolRouter<Server>,
}

impl Server {
    fn new(idx: RfcIndex) -> Self {
        Self {
            idx: Arc::new(Mutex::new(idx)),
            tool_router: Self::tool_router(),
        }
    }

    /// Run a closure that needs `&mut RfcIndex` on a blocking thread, returning
    /// its result via the async runtime.
    async fn blocking_mut<T, F>(&self, f: F) -> Result<T, McpError>
    where
        T: Send + 'static,
        F: FnOnce(&mut RfcIndex) -> rfc_index::Result<T> + Send + 'static,
    {
        let idx = self.idx.clone();
        tokio::task::spawn_blocking(move || {
            let mut guard = idx.lock().expect("RfcIndex mutex poisoned");
            f(&mut guard)
        })
        .await
        .map_err(|e| McpError::internal_error(format!("blocking task: {e}"), None))?
        .map_err(|e| McpError::internal_error(e.to_string(), None))
    }

    /// Same as `blocking_mut` but for read-only `&RfcIndex` operations.
    async fn blocking<T, F>(&self, f: F) -> Result<T, McpError>
    where
        T: Send + 'static,
        F: FnOnce(&RfcIndex) -> rfc_index::Result<T> + Send + 'static,
    {
        let idx = self.idx.clone();
        tokio::task::spawn_blocking(move || {
            let guard = idx.lock().expect("RfcIndex mutex poisoned");
            f(&guard)
        })
        .await
        .map_err(|e| McpError::internal_error(format!("blocking task: {e}"), None))?
        .map_err(|e| McpError::internal_error(e.to_string(), None))
    }
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct NumberArg {
    /// RFC number (e.g. 9000)
    number: u32,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SearchArgs {
    /// FTS5 query: phrases with quotes, AND/OR/NOT, NEAR(), column filters
    /// (e.g. `title:QUIC`).
    query: String,
    /// Maximum results to return.
    #[serde(default = "default_search_limit")]
    limit: usize,
}

fn default_search_limit() -> usize {
    20
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ListArgs {
    /// Case-insensitive regex applied to the RFC title.
    #[serde(default)]
    title_regex: Option<String>,
    /// Inclusive lower bound on publication year.
    #[serde(default)]
    min_year: Option<i32>,
    /// Inclusive upper bound on publication year.
    #[serde(default)]
    max_year: Option<i32>,
    /// Case-insensitive substring match against current_status.
    #[serde(default)]
    status_contains: Option<String>,
    /// Restrict to RFCs whose XML source is available.
    #[serde(default)]
    xml_only: bool,
    /// IETF working-group acronym (e.g. "pkix"). Case-insensitive exact match.
    #[serde(default)]
    wg: Option<String>,
    /// IETF area code (e.g. "sec"). Case-insensitive exact match.
    #[serde(default)]
    area: Option<String>,
    /// Publication stream (e.g. "IETF", "IRTF", "Independent").
    /// Case-insensitive exact match.
    #[serde(default)]
    stream: Option<String>,
    /// Editor-assigned keyword (matches an entry in the published <kw> list).
    /// Case-insensitive exact match.
    #[serde(default)]
    keyword: Option<String>,
    /// Case-insensitive regex applied to any author name.
    #[serde(default)]
    author_regex: Option<String>,
    /// Case-insensitive regex applied to the abstract text.
    #[serde(default)]
    abstract_regex: Option<String>,
    /// Restrict to RFCs that are members of any sub-series of this kind:
    /// "bcp", "std", or "fyi".
    #[serde(default)]
    series: Option<String>,
    /// Exclude RFCs that have been obsoleted by another RFC.
    #[serde(default)]
    not_obsoleted: bool,
    /// Maximum results to return.
    #[serde(default = "default_list_limit")]
    limit: usize,
}

fn default_list_limit() -> usize {
    50
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct FacetsArgs {
    /// Which facet to enumerate. One of: "wg", "area", "stream", "keyword",
    /// "status".
    kind: String,
    /// Case-insensitive substring filter on the facet value (e.g. "pkix" to
    /// find a working group whose acronym contains "pkix").
    #[serde(default)]
    contains: Option<String>,
    /// Maximum facet values to return.
    #[serde(default = "default_facets_limit")]
    limit: usize,
}

fn default_facets_limit() -> usize {
    50
}

fn parse_series_kind(s: &str) -> Result<SeriesKind, String> {
    match s.trim().to_ascii_uppercase().as_str() {
        "BCP" => Ok(SeriesKind::Bcp),
        "STD" => Ok(SeriesKind::Std),
        "FYI" => Ok(SeriesKind::Fyi),
        other => Err(format!(
            "unknown series kind {other:?}; expected bcp/std/fyi"
        )),
    }
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct BodyArgs {
    /// RFC number.
    number: u32,
    /// If set, return only the named section (e.g. "5.2").
    #[serde(default)]
    section: Option<String>,
    /// If true, error instead of fetching from the network when not cached.
    #[serde(default)]
    no_fetch: bool,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct RefsArgs {
    /// RFC number.
    number: u32,
    /// "outgoing" (default): RFCs this body references. "incoming": RFCs whose
    /// cached bodies reference this one (limited to bodies you've fetched).
    #[serde(default)]
    direction: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct SubSeriesArgs {
    /// "BCP14", "STD3", "FYI4", or canonical form like "BCP0014".
    id: String,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
struct ErrataArgs {
    /// RFC number.
    number: u32,
    /// Optional case-insensitive substring filter on errata status (e.g.
    /// "verified", "held", "reported", "rejected").
    #[serde(default)]
    status: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum RefsDirection {
    Outgoing,
    Incoming,
}

fn parse_refs_direction(direction: Option<&str>) -> Result<RefsDirection, String> {
    match direction {
        None => Ok(RefsDirection::Outgoing),
        Some(s)
            if s.eq_ignore_ascii_case("outgoing")
                || s.eq_ignore_ascii_case("out")
                || s.eq_ignore_ascii_case("from") =>
        {
            Ok(RefsDirection::Outgoing)
        }
        Some(s)
            if s.eq_ignore_ascii_case("incoming")
                || s.eq_ignore_ascii_case("in")
                || s.eq_ignore_ascii_case("to") =>
        {
            Ok(RefsDirection::Incoming)
        }
        Some(s) => Err(format!(
            "invalid direction {s:?}; expected outgoing/out/from or incoming/in/to"
        )),
    }
}

#[tool_router]
impl Server {
    #[tool(
        description = "Get metadata for an RFC: title, authors, date, status, stream, \
                       abstract, formats, errata flag, and obsoletes/updates relations \
                       from the published index. Does NOT fetch the body."
    )]
    async fn get_rfc(
        &self,
        Parameters(args): Parameters<NumberArg>,
    ) -> Result<CallToolResult, McpError> {
        let n = args.number;
        let r = self
            .blocking(move |idx| idx.get(n))
            .await?
            .ok_or_else(|| McpError::invalid_request(format!("RFC {n} not in index"), None))?;
        Ok(json_result(rfc_to_json(&r)))
    }

    #[tool(
        description = "Full-text search across RFC title, abstract, keywords, and (when \
                       cached) body. Returns ranked matches with snippets. The query is \
                       passed verbatim to SQLite FTS5: phrases use double quotes, \
                       AND/OR/NOT and NEAR() are supported, and column filters like \
                       `title:QUIC` restrict matches to one field."
    )]
    async fn search(
        &self,
        Parameters(args): Parameters<SearchArgs>,
    ) -> Result<CallToolResult, McpError> {
        let SearchArgs { query, limit } = args;
        let lim = if limit == 0 { None } else { Some(limit) };
        let hits = self.blocking(move |idx| idx.search(&query, lim)).await?;
        let payload: Vec<Value> = hits
            .iter()
            .map(|h| {
                json!({
                    "number": h.number(),
                    "title": h.title(),
                    "snippet": h.snippet(),
                    "score": h.score(),
                })
            })
            .collect();
        Ok(json_result(json!({ "hits": payload })))
    }

    #[tool(
        description = "List RFCs matching filters, ordered by RFC number. Filters compose \
                       with logical AND; regex filters are case-insensitive. Useful for \
                       *discovery* — combine `wg`, `area`, `stream`, `keyword`, \
                       `author_regex`, `abstract_regex`, `series`, year bounds, and the \
                       `not_obsoleted` flag to find the set of RFCs relevant to a topic. \
                       Pair with `list_facets` to learn what filter values exist."
    )]
    async fn list_rfcs(
        &self,
        Parameters(args): Parameters<ListArgs>,
    ) -> Result<CallToolResult, McpError> {
        let series = match args.series.as_deref() {
            None => None,
            Some(s) => {
                Some(parse_series_kind(s).map_err(|msg| McpError::invalid_request(msg, None))?)
            }
        };
        let q = RfcQuery {
            title_regex: args.title_regex,
            min_year: args.min_year,
            max_year: args.max_year,
            status_contains: args.status_contains,
            xml_only: args.xml_only,
            wg: args.wg,
            area: args.area,
            stream: args.stream,
            keyword: args.keyword,
            author_regex: args.author_regex,
            abstract_regex: args.abstract_regex,
            series,
            not_obsoleted: args.not_obsoleted,
            limit: Some(args.limit),
        };
        let rfcs = self.blocking(move |idx| idx.list(&q)).await?;
        let payload: Vec<Value> = rfcs
            .iter()
            .map(|r| {
                json!({
                    "number": r.number(),
                    "title": r.title(),
                    "year": r.date().map(|d| d.year),
                    "status": r.current_status(),
                    "wg": r.wg(),
                    "area": r.area(),
                    "stream": r.stream(),
                    "has_xml": r.has_xml(),
                })
            })
            .collect();
        Ok(json_result(json!({ "rfcs": payload })))
    }

    #[tool(
        description = "Enumerate distinct values of a discoverable facet, with the count \
                       of RFCs carrying each value. Use this to discover what filter \
                       values exist before drilling in via `list_rfcs`. \
                       Recognised `kind`: \"wg\" (working group), \"area\" (IETF area), \
                       \"stream\", \"keyword\", \"status\". Optional `contains` is a \
                       case-insensitive substring filter on the facet value."
    )]
    async fn list_facets(
        &self,
        Parameters(args): Parameters<FacetsArgs>,
    ) -> Result<CallToolResult, McpError> {
        let kind = FacetKind::parse(&args.kind).ok_or_else(|| {
            McpError::invalid_request(
                format!(
                    "unknown facet {:?}; expected wg/area/stream/keyword/status",
                    args.kind
                ),
                None,
            )
        })?;
        let contains = args.contains.clone();
        let limit = args.limit;
        let facets = self
            .blocking(move |idx| idx.facets(kind, contains.as_deref()))
            .await?;
        let total = facets.len();
        let take = if limit == 0 { total } else { limit };
        let arr: Vec<Value> = facets
            .into_iter()
            .take(take)
            .map(|f| json!({ "value": f.value(), "count": f.count() }))
            .collect();
        Ok(json_result(json!({
            "kind": kind.as_slug(),
            "total": total,
            "facets": arr,
        })))
    }

    #[tool(
        description = "Return the rendered text of an RFC body, or just one section if \
                       `section` is given (e.g. \"5.2\" — includes descendants like 5.2.1, \
                       stops at next sibling). Auto-fetches and caches the body unless \
                       `no_fetch` is true. Prefer this over downloading RFCs by URL: it's \
                       cached, stable, and supports section addressing."
    )]
    async fn get_body(
        &self,
        Parameters(args): Parameters<BodyArgs>,
    ) -> Result<CallToolResult, McpError> {
        let BodyArgs {
            number,
            section,
            no_fetch,
        } = args;
        let body = if no_fetch {
            self.blocking(move |idx| idx.body(number))
                .await?
                .ok_or_else(|| {
                    McpError::invalid_request(format!("RFC {number} body not cached"), None)
                })?
        } else {
            self.blocking_mut(move |idx| idx.ensure_body(number))
                .await?
        };

        let text = if let Some(num) = section {
            body.section(&num)
                .map(|s| s.text.to_string())
                .ok_or_else(|| {
                    McpError::invalid_request(
                        format!("section {num} not found in RFC {number}"),
                        None,
                    )
                })?
        } else {
            body.text().to_string()
        };
        Ok(CallToolResult::success(vec![Content::text(text)]))
    }

    #[tool(
        description = "List section numbers and titles detected in an RFC body. \
                       Auto-fetches the body if not cached."
    )]
    async fn list_sections(
        &self,
        Parameters(args): Parameters<NumberArg>,
    ) -> Result<CallToolResult, McpError> {
        let n = args.number;
        let body = self.blocking_mut(move |idx| idx.ensure_body(n)).await?;
        let sections: Vec<Value> = body
            .sections()
            .into_iter()
            .map(|s| json!({"number": s.number, "title": s.title}))
            .collect();
        Ok(json_result(json!({ "rfc": n, "sections": sections })))
    }

    #[tool(
        description = "Body-derived references for an RFC. `direction=\"outgoing\"` \
                       (default) returns RFCs cited from this RFC's body; \
                       `direction=\"incoming\"` returns RFCs (from your local body cache) \
                       that cite this one."
    )]
    async fn references(
        &self,
        Parameters(args): Parameters<RefsArgs>,
    ) -> Result<CallToolResult, McpError> {
        let RefsArgs { number, direction } = args;
        let direction = parse_refs_direction(direction.as_deref())
            .map_err(|msg| McpError::invalid_request(msg, None))?;
        let incoming = matches!(direction, RefsDirection::Incoming);
        let nums = self
            .blocking(move |idx| {
                if incoming {
                    idx.referenced_by(number)
                } else {
                    idx.references(number)
                }
            })
            .await?;
        let payload = self
            .blocking(move |idx| {
                let mut out = Vec::with_capacity(nums.len());
                for n in nums {
                    let title = idx.get(n)?.map(|r| r.title().to_string());
                    out.push((n, title));
                }
                Ok(out)
            })
            .await?;
        let arr: Vec<Value> = payload
            .into_iter()
            .map(|(n, t)| json!({"number": n, "title": t}))
            .collect();
        Ok(json_result(json!({
            "rfc": number,
            "direction": if incoming { "incoming" } else { "outgoing" },
            "rfcs": arr,
        })))
    }

    #[tool(
        description = "Look up a sub-series document (BCP, STD, or FYI). Accepts \
                       \"BCP14\", \"STD3\", \"FYI4\", \"BCP 14\", or canonical \"BCP0014\". \
                       Returns the title and member RFC numbers."
    )]
    async fn get_sub_series(
        &self,
        Parameters(args): Parameters<SubSeriesArgs>,
    ) -> Result<CallToolResult, McpError> {
        let id = args.id.clone();
        let sub = self
            .blocking(move |idx| idx.get_sub_series(&id))
            .await?
            .ok_or_else(|| McpError::invalid_request(format!("{} not found", args.id), None))?;
        let members = sub.members().to_vec();
        let titled = self
            .blocking(move |idx| {
                let mut out = Vec::with_capacity(members.len());
                for n in members {
                    let title = idx.get(n)?.map(|r| r.title().to_string());
                    out.push((n, title));
                }
                Ok(out)
            })
            .await?;
        let arr: Vec<Value> = titled
            .into_iter()
            .map(|(n, t)| json!({"number": n, "title": t}))
            .collect();
        Ok(json_result(json!({
            "doc_id": sub.doc_id(),
            "series": sub.series().as_str(),
            "number": sub.number(),
            "title": sub.title(),
            "members": arr,
        })))
    }

    #[tool(
        description = "Return cached errata for an RFC. Optional `status` filter is a \
                       case-insensitive substring (e.g. \"verified\", \"held\"). Run \
                       `sync_errata` first to populate the cache."
    )]
    async fn get_errata(
        &self,
        Parameters(args): Parameters<ErrataArgs>,
    ) -> Result<CallToolResult, McpError> {
        let n = args.number;
        let mut errata = self.blocking(move |idx| idx.errata(n)).await?;
        if let Some(s) = &args.status {
            let needle = s.to_lowercase();
            errata.retain(|e| e.status().to_lowercase().contains(&needle));
        }
        let arr: Vec<Value> = errata
            .iter()
            .map(|e| {
                json!({
                    "eid": e.eid(),
                    "rfc": e.rfc(),
                    "status": e.status(),
                    "kind": e.kind(),
                    "section": e.section(),
                    "orig_text": e.orig_text(),
                    "correct_text": e.correct_text(),
                    "notes": e.notes(),
                    "submitted": e.submitted(),
                    "updated": e.updated(),
                    "submitter": e.submitter(),
                    "verifier": e.verifier(),
                })
            })
            .collect();
        Ok(json_result(json!({ "rfc": n, "errata": arr })))
    }

    #[tool(
        description = "Refresh the local RFC metadata index from rfc-editor.org. Sends \
                       conditional GET; returns `not_modified=true` when the upstream \
                       index hasn't changed."
    )]
    async fn sync_index(&self) -> Result<CallToolResult, McpError> {
        let stats = self.blocking_mut(|idx| idx.sync_index()).await?;
        Ok(json_result(json!({
            "rfcs": stats.rfcs,
            "bcps": stats.bcps,
            "stds": stats.stds,
            "fyis": stats.fyis,
            "bytes": stats.bytes,
            "not_modified": stats.not_modified,
        })))
    }

    #[tool(description = "Refresh the local errata cache from rfc-editor.org's errata.json.")]
    async fn sync_errata(&self) -> Result<CallToolResult, McpError> {
        let stats = self.blocking_mut(|idx| idx.sync_errata()).await?;
        Ok(json_result(json!({
            "errata": stats.errata,
            "bytes": stats.bytes,
            "not_modified": stats.not_modified,
        })))
    }
}

#[tool_handler]
impl ServerHandler for Server {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2024_11_05)
            .with_instructions(
                "Local RFC index and cache. Use `search` for keyword/topic queries; \
             `get_rfc` for an RFC's metadata; `get_body` (with optional `section`) \
             for the rendered text; `references` to follow citation edges; \
             `get_sub_series` for BCP/STD/FYI lookups; `get_errata` for published \
             errata. For *discovery* (\"what RFCs are relevant to topic X?\"), use \
             `list_facets` to learn what working groups/areas/keywords exist, then \
             `list_rfcs` with the corresponding filters (`wg`, `area`, `keyword`, \
             `author_regex`, `abstract_regex`, `series`, `not_obsoleted`, ...). \
             Bodies are fetched on demand and cached locally — prefer these tools \
             over scraping URLs from rfc-editor.org."
                    .to_string(),
            )
    }
}

fn rfc_to_json(r: &rfc_index::Rfc) -> Value {
    json!({
        "number": r.number(),
        "title": r.title(),
        "abstract": r.abstract_text(),
        "date": r.date().map(|d| json!({"year": d.year, "month": d.month})),
        "page_count": r.page_count(),
        "draft": r.draft(),
        "current_status": r.current_status(),
        "publication_status": r.publication_status(),
        "stream": r.stream(),
        "area": r.area(),
        "wg": r.wg(),
        "doi": r.doi(),
        "has_errata": r.has_errata(),
        "formats": r.formats(),
        "has_xml": r.has_xml(),
        "authors": r.authors().iter().map(|a| json!({"name": a.name(), "role": a.role()})).collect::<Vec<_>>(),
        "keywords": r.keywords(),
        "obsoletes": r.obsoletes(),
        "obsoleted_by": r.obsoleted_by(),
        "updates": r.updates(),
        "updated_by": r.updated_by(),
        "sub_series": r.sub_series().iter().map(|s| json!({"doc_id": s.doc_id(), "title": s.title()})).collect::<Vec<_>>(),
    })
}

fn json_result(value: Value) -> CallToolResult {
    CallToolResult::success(vec![Content::text(value.to_string())])
}

fn main() -> anyhow::Result<()> {
    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()?;

    let idx = RfcIndex::open_default()?;
    let server = Server::new(idx);
    // Hold a clone outside the async block so that when `service` (and the
    // `server` it consumed) drops inside the runtime, the inner Arc<RfcIndex>
    // refcount stays >0 and the actual `reqwest::blocking::Client` drop
    // happens here in sync context. Avoids the "Cannot drop a runtime in an
    // asynchronous context" panic from reqwest::blocking's internal runtime.
    let server_handle = server.clone();

    let result = runtime.block_on(async move {
        let service = server.serve(stdio()).await?;
        service.waiting().await?;
        anyhow::Ok(())
    });

    drop(server_handle);
    runtime.shutdown_background();
    result
}

#[cfg(test)]
mod tests {
    use super::{RefsDirection, parse_refs_direction};

    #[test]
    fn parses_reference_directions() {
        assert_eq!(parse_refs_direction(None), Ok(RefsDirection::Outgoing));
        assert_eq!(
            parse_refs_direction(Some("incoming")),
            Ok(RefsDirection::Incoming)
        );
        assert_eq!(
            parse_refs_direction(Some("OUT")),
            Ok(RefsDirection::Outgoing)
        );
        assert_eq!(
            parse_refs_direction(Some("to")),
            Ok(RefsDirection::Incoming)
        );
    }

    #[test]
    fn rejects_invalid_reference_direction() {
        let err = parse_refs_direction(Some("sideways")).unwrap_err();
        assert!(err.contains("invalid direction"));
    }
}
